### ISSUE TITLE
Error parsing error from mandrill

### ISSUE THREAD

**Issue by choeflake** [rschreijer/lutung#25]
The requestdispatcher tries to read a json formatted error from a response with error status code. But the response does not contain a json formatted error. Please throw in this case an exception with the original body content.

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
        at com.google.gson.Gson.fromJson(Gson.java:803)
        at com.google.gson.Gson.fromJson(Gson.java:768)
        at com.google.gson.Gson.fromJson(Gson.java:717)
        at com.google.gson.Gson.fromJson(Gson.java:689)
        at com.microtripit.mandrillapp.lutung.model.MandrillRequestDispatcher.execute(MandrillRequestDispatcher.java:62)
        at com.microtripit.mandrillapp.lutung.controller.MandrillUtil.query(MandrillUtil.java:45)
        at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.search(MandrillMessagesApi.java:239)
        at ....mycode....
        at ....mycode....
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
        ... 11 more

**Comment by udatsnoi** [comment]
I am experiencing the same issue.

**Comment by carmudgeon** [comment]
I am experiencing the same issue.

**Comment by billoneil** [comment]
Do you know of an easy way to reproduce this so I can make a fix?

**Comment by billoneil** [comment]
@udatsnoi @carmudgeon I tried looking into this but it seems like all of the errors are coming back as json. Do you have a reproducible example where the error is not json?

**Comment by RanGold** [comment]
I looked into mandrill documentation, and it seems they only have json responses.
I assume a non json response could be caused by a communication problem.

Anyhow, the above error can be caught and handled appropriately - Internal error thrown with the mandrill response. This way, the next time it will happen we would know the real cause.

**Comment by antoinemeyer** [comment]
I am experiencing the same issue.

**Comment by billoneil** [comment]
This should do it. https://github.com/rschreijer/lutung/pull/67
