### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by albert-kam** [rschreijer/lutung#42]
I used to have mail sending through http working lutung version 0.0.2-snapshot.

After a long idle time on the app, i retry sending email from my app through lutung http api again, but it now it throws internal server error.
After upgrading to the latest 0.0.5, it throws the same exception.

Here's the trace:

```
Exception: com.microtripit.mandrillapp.lutung.model.MandrillApiError: Unexpected http status in response: 500 (Internal Server Error)
at com.microtripit.mandrillapp.lutung.model.MandrillRequestDispatcher.execute(MandrillRequestDispatcher.java:92)
at com.microtripit.mandrillapp.lutung.controller.MandrillUtil.query(MandrillUtil.java:46)
at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.sendTemplate(MandrillMessagesApi.java:206)
at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.sendTemplate(MandrillMessagesApi.java:133)
```

It used to work, so it shouldnt be about the api key or something, as i havent changed the key or anything.

What might be wrong and how do i debug it ?

Here's my code :

```
MandrillMessage message = this.createMessage(
    mailMsg.getSubject(), // the email subject / title
    ADMIN_MAIL,  // my email
    mailMsg.getVar().getDomainName() + " Admin" 
);
message.setGlobalMergeVars(this.createMergeVars(mailMsg));
message.setTo(this.createRecipients(mailMsg.getRecipients()));
message.setTags(mailMsg.getTags());

// hard code the api key here
MandrillApi mandrillApi = new MandrillApi(API_KEY);
MandrillMessageStatus[] messageStatusReports = null;
try {
    messageStatusReports = mandrillApi.messages().sendTemplate(
        mailMsg.getTemplate(), 
        null, // we got no block contents like mailchimp's templat layout 
        message, 
        false // it'll become true automatically if there're lots of recipients
    );
} catch(Exception e) {
  ...
}

return messageStatusReports;
```

Thanks a lot !

**Comment by jiks2239** [comment]
i am facing the same issue.... but couldn't get any idea.. i am not using other api key.... please help me...
