### ISSUE TITLE
Unable to send mail while using Play Framework. Works perfectly well in a normal maven Java Project

### ISSUE THREAD

**Issue by kgrbh** [rschreijer/lutung#55]
I am trying to integrate lutung with the Play Framework. The Play version is 2.4. The build.sbt is as below:

  "com.google.code.gson" % "gson" % "2.3.1",
  "org.apache.httpcomponents" % "httpclient" % "4.0-alpha4",
  "commons-io" % "commons-io" % "1.3.2",
  "commons-logging" % "commons-logging" % "1.1.1",
  "com.mandrillapp.wrapper.lutung" % "lutung" % "0.0.4"

And the code to send mail is exactly the same as the one  shown in Examples section of the repo at https://github.com/rschreijer/lutung. I am getting an Internal Server error 500. The detailed trace:
com.microtripit.mandrillapp.lutung.model.MandrillApiError: Unexpected http status in response: 500 (Internal Server Error)
	at com.microtripit.mandrillapp.lutung.model.MandrillRequestDispatcher.execute(MandrillRequestDispatcher.java:64)
	at com.microtripit.mandrillapp.lutung.controller.MandrillUtil.query(MandrillUtil.java:45)
	at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.send(MandrillMessagesApi.java:99)
	at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.send(MandrillMessagesApi.java:54)
	at controllers.MongoStore.sendMandrill(MongoStore.java:63)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$4$$anonfun$apply

The same code is working fine when i build a normal maven java (No Play Framework)project. What am i missing here?

**Comment by qstrahl** [comment]
@kgrbh Did you find a solution to this issue?
