### ISSUE TITLE
Unsupported cookie spec on Hello World Example

### ISSUE THREAD

**Issue by stephan-rayner** [rschreijer/lutung#59]
Explanation
-----------
I attempted to run the HelloWorld example from the readme and received an "Unsupported cookie spec" error at the line ...
```
MandrillMessageStatus[] messageStatusReports = mandrillApi
        .messages().send(message, false);
```

Failed Source Code
--------------------------
```
//Initiate Mandrill
MandrillApi mandrillApi = new MandrillApi("<My API Key>");

//Build Message
MandrillMessage message = new MandrillMessage();
message.setSubject("Hello World!!");
message.setHtml("<h1>Hi pal!</h1><br />Really, I'm just saying hi!");
message.setFromEmail("myPersonalEmail@thisIsAnEmail.com");
message.setFromName("Stephan Rayner Personal Email");

//Build Recipients
ArrayList<Recipient> recipients = new ArrayList<Recipient>();
Recipient recipient = new Recipient();
recipient.setEmail("myWorkEmail@thisIsAnEmail.com");
recipient.setName("Stephan Rayner Work Email");
recipients.add(recipient);

/*This is where you add more*/

// Attach Recipients to message
message.setTo(recipients);
message.setPreserveRecipients(true);

// Create And Attach Tags
ArrayList <String> tags = new ArrayList<String>();
tags.add("test");
message.setTags(tags);

/* There are more message details that can be added*/
try {
    MandrillMessageStatus[] messageStatusReports = mandrillApi
            .messages().send(message, false);

    // Iterate over responses
    for (MandrillMessageStatus statusReport: messageStatusReports) {
        _logger.info("Message Status Report: " + statusReport.getStatus());
    }
} catch (MandrillApiError e){
    _logger.error(e.getMandrillErrorAsJson(), e);
} catch (IOException e) {
    _logger.error(e.getMessage());
}
```

Stack Trace
----------------

```
java.lang.IllegalStateException: Unsupported cookie spec: default
	at org.apache.http.cookie.CookieSpecRegistry.getCookieSpec(CookieSpecRegistry.java:110)
	at org.apache.http.cookie.CookieSpecRegistry$1.create(CookieSpecRegistry.java:163)
	at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:157)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
	at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:166)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:485)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:878)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:84)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:109)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.microtripit.mandrillapp.lutung.model.MandrillRequestDispatcher.execute(MandrillRequestDispatcher.java:73)
	at com.microtripit.mandrillapp.lutung.controller.MandrillUtil.query(MandrillUtil.java:46)
	at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.send(MandrillMessagesApi.java:94)
	at com.microtripit.mandrillapp.lutung.controller.MandrillMessagesApi.send(MandrillMessagesApi.java:49)
	at <the file and line number where I called the aforementioned line>
```

**Comment by billoneil** [comment]
This is most likely an issue with the Apache HTTP client version. Make sure you don't have multiple versions on the path. http://stackoverflow.com/questions/26187341/httpget-get-new-httpgeturl-giving-exceptions
